### ISSUE TITLE
problem in discriminator

### ISSUE THREAD

**Issue by JuggerNau** [AndyHsiao26/InfoGAN-tensorflow#2]
I don't understand the parameter fix_var, but I see, in the discriminator, q_net, there is a fully connected layer about fix_var, but we didn't train this layer in the training process, so how to load our checkpoint in the test process?
When I tried the test process, it will return some error:
`NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) Not found: Key discriminator/q/fully_connected_3/biases not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/j/Info_GAN/Model.py:86) ]]
  (1) Not found: Key discriminator/q/fully_connected_3/biases not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/j/Info_GAN/Model.py:86) ]]
	 [[save/RestoreV2/_149]]`

**Comment by fangihsiao** [comment]
Hi,

The parameter fix_var means if the neural network will output the variance of the Gaussian distribution. If it is true, then the variance is fixed; otherwise there will be another fully connected layer for the variance.

Please make sure you set the same fix_var for both training and testing. If fix_var is true for training, we won't build the fully connected layer for the variance. Then if fix_var is false at test time, our graph will contain that layer but is not able to find the corresponding weights, which will result in the error.
